import 'package:flutter/material.dart';

import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';

class OnboardingPage extends StatefulWidget {
  @override
  _OnboardingPageState createState() => _OnboardingPageState();
}

class _OnboardingPageState extends State<OnboardingPage> {
  PageController _pageController = PageController();
  int currentPage = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          PageView(
            controller: _pageController,
            onPageChanged: (index) {
              setState(() {
                currentPage = index;
              });
            },
            children: [
              _buildPage(
                image: 'assets/imagen1.png', // Asegúrate de colocar las imágenes en el directorio correcto
                title: 'Manage rentals easily',
                description: 'Makes it easy to manage multiple property rentals',
              ),
              _buildPage(
                image: 'assets/imagen2.png',
                title: 'The most customer-friendly platform',
                description: 'Metrics that will help you with decision making',
              ),
              _buildPage(
                image: 'assets/imagen3.png',
                title: 'It is important to manage money well',
                description: 'Help in managing money generated by rentals',
              ),
            ],
          ),
          Positioned(
            bottom: 20,
            left: 20,
            right: 20,
            child: ElevatedButton(
              onPressed: () {
                if (currentPage < 2) {
                  _pageController.nextPage(
                    duration: Duration(milliseconds: 300),
                    curve: Curves.easeIn,
                  );
                } else {
                  // Guardar que el onboarding ya se ha visto
                  final box = GetStorage();
                  box.write('hasSeenOnboarding', true);

                  // Redirigir a la página de Login y limpiar el historial
                  Get.offAllNamed('/login');
                }
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.orange,
                padding: EdgeInsets.symmetric(vertical: 16),
              ),
              child: Text(
                currentPage == 2 ? 'Get Started' : 'Next',
                style: TextStyle(fontSize: 16),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPage({required String image, required String title, required String description}) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Image.asset(image, height: 300), // Usa tus imágenes
          SizedBox(height: 30),
          Text(
            title,
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 24),
            textAlign: TextAlign.center,
          ),
          SizedBox(height: 10),
          Text(
            description,
            style: TextStyle(fontSize: 16, color: Colors.grey),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}
